### PR TITLE
Improve competition form, fix #95

### LINKED ISSUE #95: Improve competition creation/edit form
- [x] Start and end date should be a `<input type="datetime-local" />`
- [x] Fewers rows for "description" field
- [x] Put labels on the left on large screens
- [x] Players selection should be improved with something like select2 multiple or similar.
- [x] Use full name for players selection

### PR DESCRIPTION
**Pull request by LeBenLeBen**
Fix #95

### CODE REVIEW

**Comment by LeBenLeBen** [comment]
Waiting on Select2 that should come with #107

**Comment by LeBenLeBen** [comment]
Note: don’t forget `{{ form.non_field_errors }}`

**Comment by LeBenLeBen** [comment]
@sephii Could you help me have the full name displayed instead of the username for players?

**Comment by sephii** [comment]
Done in https://github.com/team-rawbot/rank-me/pull/108/commits/f095d2b647a22349145a6d5479aa94e3412ba471

**Comment by LeBenLeBen** [comment]
Thanks !

**Pull request merged**
