### PR TITLE
Add skill and position deltas

### PR DESCRIPTION
**Pull request by Hywan**
Having delta between skill and position points can be useful if you are tired and can no longer make Maths in your head.
Also, the space before colons have been removed since this is not correct regarding English typography rules.

### CODE REVIEW

**Comment by LeBenLeBen** [comment]
I’ve got cases in which the Delta is NaN, could you please ensure it doesn’t happen?

**Comment by Hywan** [comment]
@LeBenLeBen Was it for the first delta or for another one (2nd, last)? Was it also the case for the skill value?

**Comment by LeBenLeBen** [comment]
Both deltas, and deltas only.

Also it would be great to add a space before the parenthesis and limit the delta decimals to 2.

**Comment by Hywan** [comment]
I did not test my commit because I don't want to run the stack just for a single commit. I will try something.

**Pull request closed without merging**
